package ExceptionHandling;

public class FinallyBlock {
	public static void main(String[] args) {
		try {
			int a=1/2;
		}
		catch (ArithmeticException e) {
			// TODO: handle exception
			System.out.println("Handled");
		}
		
		
		finally {
			System.out.println("It's finally block ");
		}
	}

}
